### ISSUE TITLE
testTravelAgencyService should be added back once the test command is fixed

### ISSUE THREAD

**Issue by arukshani** [ballerina-guides/parallel-service-orchestration#24]
Commit >> 69075a6b52f97e3a8bf0bc78acc6476579875b52

**Comment by ThisaruGuruge** [comment]
This is temporally fixed using different ports in the test (9094, 9095, 9096), should change the port numbers back to (9091, 9092, 9093) once the fix is done on [this issue](https://github.com/ballerina-platform/ballerina-lang/issues/12553)

**Comment by anupama-pathirage** [comment]
Closing as we no longer maintain this repo.
